export  const GET_USERS_FETCHING = "GET_USERS_FETCHING";
export  const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export  const GET_USERS_FILED = "GET_USERS_FILED";
export  const SET_CURRENT_NUMBER = "SET_CURRENT_NUMBER";
export  const SET_USERS_SUCCESS = "SET_USERS_SUCCESS";
export  const SET_USERS_FETCHING = "GET_USERS_FETCHING";
export  const SET_USERS_FILED = "SET_USERS_FILED";
export  const PUT_USERS_SUCCESS = "PUT_USERS_SUCCESS";
export  const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export  const DELETE_USERS_FILED = "DELETE_USERS_FILED";
export  const PUT_USERS_FILED = "PUT_USERS_FILED";

